export const COURSE_CREATE = "COURSE_CREATE";
export const COURSE_CREATE_SUCCESS = "COURSE_CREATE_SUCCESS";
export const LOAD_COURSE = "LOAD_COURSE_SUCCESS";
export const LOAD_AUTHORS = "LOAD_AUTHORS_SUCCESS";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const API_STATUS_BEGIN = "API_STATUS_BEGIN";
export const API_CALL_ERROR = "API_CALL_ERROR";

