export const COURSE_CREATE = "COURSE_CREATE";
export const COURSE_CREATE_SUCCESS = "COURSE_CREATE_SUCCESS";
export const LOAD_COURSE = "LOAD_COURSE";
export const LOAD_AUTHORS = "LOAD_AUTHORS";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS"